print("Registration: Please enter correct credidentials.")
first_name = input("Please enter your first name: ")
Middle_initial= input("please enter your middle_initial:")
Last_name= input("please enter your last name:")
street_adress= input("please enter your street_address:")
city= input("please enter your city:")
state_abbreviation= input("please enter state_abbreviation:")
zip_code= input ("please enter your zip_code:")
phone_number= input ("please enter your phone number:")
email_address= input ("please enter your email_address:")
print("")

print("JNP N Depp")
print("221B Baker Street")
print("City Of Westminster, UK SW1")
print("555 123 4567")
print("jnd@gmail.com")
